# Generated by Django 3.0.3 on 2020-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_folder',
            field=models.CharField(max_length=255, null=True, verbose_name='Расположение проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_identifier',
            field=models.CharField(max_length=255, null=True, verbose_name='Идентификатор проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[['simple_web', 'Простой веб-приложение (HTML/CSS/JS)'], ['reactjs_web', 'ReactJS веб-приложение'], ['nodejs_web', 'NodeJS веб-сервер'], ['simple_python', 'Python с стандартной библиотекой'], ['django_python', 'Django веб-сервер'], ['pygame_python', 'Создание графической игры (pygame)'], ['simple_php', 'Веб-сервер с PHP и MySQL'], ['wordpress_php', 'CMS WordPress'], ['laravel_php', 'Фреймворк Laravel']], max_length=128, verbose_name='Тип проекта'),
        ),
    ]
