class SOCKET_TYPES:
    READY = 'READY'
    EXPLORER_UPDATE = 'EXPLORER_UPDATE'
    RUN_SERVER = 'RUN_SERVER'
    FILE_OPEN = 'FILE_OPEN'
    FILE_SAVE = 'FILE_SAVE'
    FILE_CREATE = 'FILE_CREATE'
    FOLDER_CREATE = 'FOLDER_CREATE'


class STATUS:
    SUCCESS = 'SUCCESS'